In [1]:
print('hello world')

hello world


In [2]:
x=11
print(x)

11


In [3]:
import numpy as np

In [4]:
a=np.array([1,2,3,4,5,6])

In [5]:
type(a)

numpy.ndarray

In [6]:
a.ndim

1

In [7]:
a.shape

(6,)

In [8]:
a=range(1,11,0.2)

TypeError: 'float' object cannot be interpreted as an integer

In [9]:
a=np.arange(1,11,0.2)

In [10]:
a

array([ 1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,  2.6,  2.8,  3. ,
        3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,
        5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,
        7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,
        9.8, 10. , 10.2, 10.4, 10.6, 10.8])

In [11]:
type a

SyntaxError: invalid syntax (<ipython-input-11-1d67122640cd>, line 1)

In [12]:
type(a)

numpy.ndarray

In [13]:
b=np.arange(15)

In [14]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
b.ndim,b.shape

(1, (15,))

In [16]:
c=b.reshape(3,5)

In [18]:
b.ndim,b.shape

(1, (15,))

In [19]:
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [20]:
c.ndim,c.shape

(2, (3, 5))

In [21]:
c[2][4]

14

In [22]:
c.dtype

dtype('int32')

In [23]:
d.dtype

NameError: name 'd' is not defined

In [36]:
d=np.array([1.2,4,2.,3])

In [28]:
d=np.array([1,2,3,4.4])

In [29]:
d.dtype

dtype('float64')

In [30]:
e=c.ravel()

In [31]:
e.ndim

1

In [32]:
e.shape

(15,)

In [34]:
k=np.zeros((3,6))

In [35]:
k

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [37]:
q=np.ones((3,6))

In [38]:
q

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [39]:
l=np.linspace(1,10,500)

In [40]:
l

array([ 1.        ,  1.01803607,  1.03607214,  1.05410822,  1.07214429,
        1.09018036,  1.10821643,  1.12625251,  1.14428858,  1.16232465,
        1.18036072,  1.19839679,  1.21643287,  1.23446894,  1.25250501,
        1.27054108,  1.28857715,  1.30661323,  1.3246493 ,  1.34268537,
        1.36072144,  1.37875752,  1.39679359,  1.41482966,  1.43286573,
        1.4509018 ,  1.46893788,  1.48697395,  1.50501002,  1.52304609,
        1.54108216,  1.55911824,  1.57715431,  1.59519038,  1.61322645,
        1.63126253,  1.6492986 ,  1.66733467,  1.68537074,  1.70340681,
        1.72144289,  1.73947896,  1.75751503,  1.7755511 ,  1.79358717,
        1.81162325,  1.82965932,  1.84769539,  1.86573146,  1.88376754,
        1.90180361,  1.91983968,  1.93787575,  1.95591182,  1.9739479 ,
        1.99198397,  2.01002004,  2.02805611,  2.04609218,  2.06412826,
        2.08216433,  2.1002004 ,  2.11823647,  2.13627255,  2.15430862,
        2.17234469,  2.19038076,  2.20841683,  2.22645291,  2.24